### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LuxCodingFivem** [BigSmoKe07/bs_recycling#1]
hey i got this error 

https://gyazo.com/c81e8b3d834bc953a47a87df27f2f43e

**Comment by BigSmoKe07** [comment]
What's your Config.recyclingMachineModel ?

**Comment by BigSmoKe07** [comment]
> I didn't change anything in the config
> 
> Config.recyclingMachineModel = "prop_planer_01" -- Defines the model of the recycling machine

Whats your changes in config.lua
