### ISSUE TITLE
[script:bs_recycling] SCRIPT ERROR: @bs_recycling/server/sv_main.lua:13: bad argument #1 to 'for iterator' (table expected, got number)

### ISSUE THREAD

**Issue by LenaMatoi** [BigSmoKe07/bs_recycling#2]
[script:bs_recycling] SCRIPT ERROR: @bs_recycling/server/sv_main.lua:13: bad argument #1 to 'for iterator' (table expected, got number)
I'm getting that error since I started the script.
It does not process the elements and throws that error

**Comment by BigSmoKe07** [comment]
Is this happen when there is not item present in the stash?

**Comment by BigSmoKe07** [comment]
This may due to the Search function return nil value, Will add a check  for that in the next update
